### ISSUE TITLE
请问上科大的算法课ppt还有吗？

### ISSUE THREAD

**Issue by yzj-again** [yanxinhao/DataStructure-Algorithm#2]
请问上科大的算法课ppt还有吗？
目前网址打不开

**Comment by yanxinhao** [comment]
我的服务器目前下线了。我过两天有时间上传到网盘吧，好了我再close issue

**Comment by yzj-again** [comment]
thanks!

**Comment by yzj-again** [comment]
您好，请问你修复好网盘服务器了吗？还有我想问一下学长上岸上科大了吗？

**Comment by yanxinhao** [comment]
我的网盘服务器在上科大没有公网ip了，外面访问不了了，你要不找上一个老哥要一份吧。我考上了，预祝你也成功

**Comment by yanxinhao** [comment]
其实你直接看清华的课程和课件就行了，关于NP问题那章就看南大的。都在b站上有资源的

**Comment by yzj-again** [comment]
您好，请问能下载下来一份传到百度云吗？

**Comment by Yokeagoni** [comment]
谢谢大佬。感谢

**Comment by yzj-again** [comment]
上个老哥目前联系不上呀。

**Comment by yanxinhao** [comment]
https://howieserver.asuscomm.com:8283/s/MxEwnDKi54qe4PB
这个是新的地址，文件已经上传，小文件很多一次全部下载可能比较慢，各取所需吧。尽快下载吧，我也不知道服务器啥时候会再次宕机

**Comment by Yokeagoni** [comment]
谢谢老哥
